services:
  dashboardfaskes:
    container_name: dashboardfaskes
    image: dashboardfaskes
    # ports:
    #   - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
        - DASHBOARD_FASKES_BASE_URL=${DASHBOARD_FASKES_BASE_URL}
        - DASHBOARD_FASKES_TOKEN=${DASHBOARD_FASKES_TOKEN}
    volumes:
      - modules_dashboardfaskes:/app/node_modules
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - proxy

volumes:
  modules_dashboardfaskes:
    driver: local

networks:
  proxy:
    external: true
    name: proxynet
